### ISSUE TITLE
Powershell 

### ISSUE THREAD

**Issue by Timohiho** [MicrosoftDocs/Contribute.de-DE#2]
I have found in the Powershell an invalid website link, the link under the notes in the help to Get-Wmi is invalid.
[https://go.microsoft.com/fwlink/?LinkID=113337](https://go.microsoft.com/fwlink/?LinkID=113337
)
The automatic redirect leads to the [https://docs.microsoft.com/en-ch/powershell/module/5.1/microsoft.powershell.management/Get-WmiObject](https://docs.microsoft.com/en-ch/powershell/module/5.1/microsoft.powershell.management/Get-WmiObject) website, but this is invalid.

![invalid_website](https://user-images.githubusercontent.com/34097483/45810648-61344a80-bccb-11e8-939d-68ea8bdf4477.png)

![invalid_website_browser](https://user-images.githubusercontent.com/34097483/45810858-f9caca80-bccb-11e8-8e13-321dcf32973e.png)

**Comment by LisandroSu** [comment]
Hello, @Timohiho 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
