### ISSUE TITLE
This page should give a hint, how to produce the documentation for (even internal) readers

### ISSUE THREAD

**Issue by bwl21** [MicrosoftDocs/Contribute.de-DE#3]
I would like to use this for our internal documentation, maintained in an internal git repository. Is this possible? and if yes,  it would be nice if this page has a link to an insttruction, how to do this.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7b26339c-9a3c-de93-7806-3eb105b16ae4
* Version Independent ID: ec4aa25b-c7e2-db46-3cf1-7563e8031bd6
* Content: [Docs Authoring Pack für Visual Studio Code - Contributor Guide](https://docs.microsoft.com/de-de/contribute/how-to-write-docs-auth-pack)
* Content Source: [Contribute/how-to-write-docs-auth-pack.md](https://github.com/MicrosoftDocs/Contribute.de-DE/blob/live/Contribute/how-to-write-docs-auth-pack.md)
* GitHub Login: @meganbradley
* Microsoft Alias: **mbradley**

**Comment by CeciAc** [comment]
Hello, @bwl21 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
